"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class alias_cmd_t(object):
    __slots__ = ["ip", "alias", "timestamp"]

    __typenames__ = ["string", "string", "int64_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.ip = ""
        self.alias = ""
        self.timestamp = 0

    def encode(self):
        buf = BytesIO()
        buf.write(alias_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __ip_encoded = self.ip.encode('utf-8')
        buf.write(struct.pack('>I', len(__ip_encoded)+1))
        buf.write(__ip_encoded)
        buf.write(b"\0")
        __alias_encoded = self.alias.encode('utf-8')
        buf.write(struct.pack('>I', len(__alias_encoded)+1))
        buf.write(__alias_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.timestamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != alias_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return alias_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = alias_cmd_t()
        __ip_len = struct.unpack('>I', buf.read(4))[0]
        self.ip = buf.read(__ip_len)[:-1].decode('utf-8', 'replace')
        __alias_len = struct.unpack('>I', buf.read(4))[0]
        self.alias = buf.read(__alias_len)[:-1].decode('utf-8', 'replace')
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if alias_cmd_t in parents: return 0
        tmphash = (0xb4a9868bd56b7318) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if alias_cmd_t._packed_fingerprint is None:
            alias_cmd_t._packed_fingerprint = struct.pack(">Q", alias_cmd_t._get_hash_recursive([]))
        return alias_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", alias_cmd_t._get_packed_fingerprint())[0]

