"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class attack_cmd_t(object):
    __slots__ = ["command", "payload_json", "timestamp", "script_inline", "script_filename", "script_id"]

    __typenames__ = ["string", "string", "int64_t", "string", "string", "string"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.command = ""
        self.payload_json = ""
        self.timestamp = 0
        self.script_inline = ""
        self.script_filename = ""
        self.script_id = ""

    def encode(self):
        buf = BytesIO()
        buf.write(attack_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __command_encoded = self.command.encode('utf-8')
        buf.write(struct.pack('>I', len(__command_encoded)+1))
        buf.write(__command_encoded)
        buf.write(b"\0")
        __payload_json_encoded = self.payload_json.encode('utf-8')
        buf.write(struct.pack('>I', len(__payload_json_encoded)+1))
        buf.write(__payload_json_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.timestamp))
        __script_inline_encoded = self.script_inline.encode('utf-8')
        buf.write(struct.pack('>I', len(__script_inline_encoded)+1))
        buf.write(__script_inline_encoded)
        buf.write(b"\0")
        __script_filename_encoded = self.script_filename.encode('utf-8')
        buf.write(struct.pack('>I', len(__script_filename_encoded)+1))
        buf.write(__script_filename_encoded)
        buf.write(b"\0")
        __script_id_encoded = self.script_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__script_id_encoded)+1))
        buf.write(__script_id_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != attack_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return attack_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = attack_cmd_t()
        __command_len = struct.unpack('>I', buf.read(4))[0]
        self.command = buf.read(__command_len)[:-1].decode('utf-8', 'replace')
        __payload_json_len = struct.unpack('>I', buf.read(4))[0]
        self.payload_json = buf.read(__payload_json_len)[:-1].decode('utf-8', 'replace')
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __script_inline_len = struct.unpack('>I', buf.read(4))[0]
        self.script_inline = buf.read(__script_inline_len)[:-1].decode('utf-8', 'replace')
        __script_filename_len = struct.unpack('>I', buf.read(4))[0]
        self.script_filename = buf.read(__script_filename_len)[:-1].decode('utf-8', 'replace')
        __script_id_len = struct.unpack('>I', buf.read(4))[0]
        self.script_id = buf.read(__script_id_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if attack_cmd_t in parents: return 0
        tmphash = (0x88adc07cfeb97461) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if attack_cmd_t._packed_fingerprint is None:
            attack_cmd_t._packed_fingerprint = struct.pack(">Q", attack_cmd_t._get_hash_recursive([]))
        return attack_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", attack_cmd_t._get_packed_fingerprint())[0]

