"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class extract_cmd_t(object):
    __slots__ = ["command", "file", "timestamp"]

    __typenames__ = ["string", "string", "int64_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.command = ""
        self.file = ""
        self.timestamp = 0

    def encode(self):
        buf = BytesIO()
        buf.write(extract_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __command_encoded = self.command.encode('utf-8')
        buf.write(struct.pack('>I', len(__command_encoded)+1))
        buf.write(__command_encoded)
        buf.write(b"\0")
        __file_encoded = self.file.encode('utf-8')
        buf.write(struct.pack('>I', len(__file_encoded)+1))
        buf.write(__file_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.timestamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != extract_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return extract_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = extract_cmd_t()
        __command_len = struct.unpack('>I', buf.read(4))[0]
        self.command = buf.read(__command_len)[:-1].decode('utf-8', 'replace')
        __file_len = struct.unpack('>I', buf.read(4))[0]
        self.file = buf.read(__file_len)[:-1].decode('utf-8', 'replace')
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if extract_cmd_t in parents: return 0
        tmphash = (0x41bcc187eb4b3bb3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if extract_cmd_t._packed_fingerprint is None:
            extract_cmd_t._packed_fingerprint = struct.pack(">Q", extract_cmd_t._get_hash_recursive([]))
        return extract_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", extract_cmd_t._get_packed_fingerprint())[0]

