"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class log_schedule(object):
    __slots__ = ["hour", "minute", "interval_hours"]

    __typenames__ = ["int32_t", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.hour = 0
        self.minute = 0
        self.interval_hours = 0

    def encode(self):
        buf = BytesIO()
        buf.write(log_schedule._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iii", self.hour, self.minute, self.interval_hours))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != log_schedule._get_packed_fingerprint():
            raise ValueError("Decode error")
        return log_schedule._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = log_schedule()
        self.hour, self.minute, self.interval_hours = struct.unpack(">iii", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if log_schedule in parents: return 0
        tmphash = (0xda3b243bc4a2231a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if log_schedule._packed_fingerprint is None:
            log_schedule._packed_fingerprint = struct.pack(">Q", log_schedule._get_hash_recursive([]))
        return log_schedule._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", log_schedule._get_packed_fingerprint())[0]

