"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class log_t(object):
    __slots__ = ["module", "level", "text", "timestamp"]

    __typenames__ = ["string", "string", "string", "int64_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.module = ""
        self.level = ""
        self.text = ""
        self.timestamp = 0

    def encode(self):
        buf = BytesIO()
        buf.write(log_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __module_encoded = self.module.encode('utf-8')
        buf.write(struct.pack('>I', len(__module_encoded)+1))
        buf.write(__module_encoded)
        buf.write(b"\0")
        __level_encoded = self.level.encode('utf-8')
        buf.write(struct.pack('>I', len(__level_encoded)+1))
        buf.write(__level_encoded)
        buf.write(b"\0")
        __text_encoded = self.text.encode('utf-8')
        buf.write(struct.pack('>I', len(__text_encoded)+1))
        buf.write(__text_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.timestamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != log_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return log_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = log_t()
        __module_len = struct.unpack('>I', buf.read(4))[0]
        self.module = buf.read(__module_len)[:-1].decode('utf-8', 'replace')
        __level_len = struct.unpack('>I', buf.read(4))[0]
        self.level = buf.read(__level_len)[:-1].decode('utf-8', 'replace')
        __text_len = struct.unpack('>I', buf.read(4))[0]
        self.text = buf.read(__text_len)[:-1].decode('utf-8', 'replace')
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if log_t in parents: return 0
        tmphash = (0x45484e476e90e1da) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if log_t._packed_fingerprint is None:
            log_t._packed_fingerprint = struct.pack(">Q", log_t._get_hash_recursive([]))
        return log_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", log_t._get_packed_fingerprint())[0]

