"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class task_status_t(object):
    __slots__ = ["task_type", "module", "state", "target", "info", "timestamp"]

    __typenames__ = ["string", "string", "string", "string", "string", "int64_t"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.task_type = ""
        self.module = ""
        self.state = ""
        self.target = ""
        self.info = ""
        self.timestamp = 0

    def encode(self):
        buf = BytesIO()
        buf.write(task_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __task_type_encoded = self.task_type.encode('utf-8')
        buf.write(struct.pack('>I', len(__task_type_encoded)+1))
        buf.write(__task_type_encoded)
        buf.write(b"\0")
        __module_encoded = self.module.encode('utf-8')
        buf.write(struct.pack('>I', len(__module_encoded)+1))
        buf.write(__module_encoded)
        buf.write(b"\0")
        __state_encoded = self.state.encode('utf-8')
        buf.write(struct.pack('>I', len(__state_encoded)+1))
        buf.write(__state_encoded)
        buf.write(b"\0")
        __target_encoded = self.target.encode('utf-8')
        buf.write(struct.pack('>I', len(__target_encoded)+1))
        buf.write(__target_encoded)
        buf.write(b"\0")
        __info_encoded = self.info.encode('utf-8')
        buf.write(struct.pack('>I', len(__info_encoded)+1))
        buf.write(__info_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.timestamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != task_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return task_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = task_status_t()
        __task_type_len = struct.unpack('>I', buf.read(4))[0]
        self.task_type = buf.read(__task_type_len)[:-1].decode('utf-8', 'replace')
        __module_len = struct.unpack('>I', buf.read(4))[0]
        self.module = buf.read(__module_len)[:-1].decode('utf-8', 'replace')
        __state_len = struct.unpack('>I', buf.read(4))[0]
        self.state = buf.read(__state_len)[:-1].decode('utf-8', 'replace')
        __target_len = struct.unpack('>I', buf.read(4))[0]
        self.target = buf.read(__target_len)[:-1].decode('utf-8', 'replace')
        __info_len = struct.unpack('>I', buf.read(4))[0]
        self.info = buf.read(__info_len)[:-1].decode('utf-8', 'replace')
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if task_status_t in parents: return 0
        tmphash = (0x7c94500a5bd95dd2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if task_status_t._packed_fingerprint is None:
            task_status_t._packed_fingerprint = struct.pack(">Q", task_status_t._get_hash_recursive([]))
        return task_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", task_status_t._get_packed_fingerprint())[0]

